name:                openapi
version:             0.1.0.0
github:              "owainlewis/openapi"
license:             BSD3
author:              "Owain Lewis"
maintainer:          "owain@owainlewis.com"
copyright:           "2019 Owain Lewis"

extra-source-files:
- README.md
description: Please see the README on GitHub at <https://github.com/owainlewis/openapi

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - text
    - bytestring
    - aeson >= 1.4.5.0
    - lens >= 4.17.1
    - hspec

tests:
  openapi-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - openapi
    - hspec
    - text
    - QuickCheck
